### ISSUE TITLE
Bound Python shell expansion doens't work properly on Linux

### ISSUE THREAD

**Issue by jasperges** [mottosso/bleeding-rez#90]
This is a continuation of [this `rez-pipz` issue](https://github.com/mottosso/rez-pipz/issues/27). As it turns out, the actual issue is with `bleeding-rez`, not `rez-pipz`.

**What fails?**
Take this for example:

```bash
rez env python
> python -c "assert True"
  File "<string>", line 1
    assert
         ^
SyntaxError: invalid syntax
```

This particular Python command (`assert True`) is just an example. The important thing is that there is a space in the command. `import sys` would also fail for example. The root cause seems to be with how `bleeding-rez` runs the commands, specifically [this part](https://github.com/mottosso/bleeding-rez/blob/master/src/rez/bind/python.py#L31-L34) which was introduced with [this commit](https://github.com/mottosso/bleeding-rez/commit/d58a7a550c55379fa2423b25b05b00c1fd764c5b).

[nerdvegas/rez](https://github.com/nerdvegas/rez) uses a [different approach](https://github.com/nerdvegas/rez/blob/master/src/rez/bind/python.py#L70), which works fine on Linux. I am curious what the reason was to deviate from that approach. @mottosso Can you shed any light on this? If it had anything to do with Windows, would it be an option to revert to the 'old' behaviour for Linux?

**Comment by mottosso** [comment]
> I am curious what the reason was to deviate from that approach

The original approach wasn't working on Windows. You can see if this has changed, by replacing [this file](https://github.com/nerdvegas/rez/blob/master/src/rez/bind/python.py) with the original. It'll make a copy of the system Python and put it in a package, as opposed to creating this `#!` file.

**Comment by mottosso** [comment]
Oh, and once you've replaced it, you can go ahead and delete the `~/packages/python` folder, and re-run `rez bind python` to re-generate it.

**Comment by jasperges** [comment]
Okay, thanks. I will check later if that works. By the way I also seem to have a fix. Replacing
```python
{python} $*
```
with
```python
{python} "$@"
```
seems to work. So adding double quotes and replacing the `*` with `@`.

Once I have done a bit more of testing, I might make a PR. :)

**Comment by mottosso** [comment]
Oo that is good. This would be preferable in a PR.

The thing about `bind`, is..

1. It's only meant for getting started; it creates packages automatically for you, that you will likely want more control over later. Especially Python. On Windows, you've got `rez-scoopz` to install a proper Python as a package, on Linux however you will need to do that manually.
2. As you'll find, `bind` is deprecated and frowned upon. It just doesn't have a viable alternative today for getting started quickly. Unless you had something like scoopz on all platforms.

With that in mind, having ` #!` file reference your system Python takes about 2ms to finish, whereas copying the local install takes longer, and that's really all that matters in terms of which to prefer. So if that fix works, that would be fantastic.
